name = "vpn"
main = "src/worker.ts"
compatibility_date = "2024-05-29"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "settings", id = "KV_NAME" }
]

# Enable Node.js compatibility
node_compat = true

# Add this to your wrangler.toml
[[build]]
# These packages will be external and not bundled
external = ["bcryptjs", "js-yaml", "crypto-js", "uuid"]
